### ISSUE TITLE
Erro build xcode 

### ISSUE THREAD

**Issue by Breners** [react-native-text-input-mask/react-native-text-input-mask#197]
fatal error: module map file '/Users/brenerdev/Library/Developer/Xcode/DerivedData/psibankapp-cwuwymaitextrogrpeyrbnllhegk/Build/Intermediates.noindex/ArchiveIntermediates/psibankapp/BuildProductsPath/Release-iphoneos/RNInputMask/RNInputMask.modulemap' not found

when i will archive on xcode, it give me this error, its ok on app

**Comment by martintreurnicht** [comment]
Should be fixed now try this build: https://github.com/react-native-text-input-mask/react-native-text-input-mask/releases/tag/v3.0.3

**Comment by danilaberentsev** [comment]
I'm getting same error in Xcode on regular build, 
"react-native-text-input-mask": "^3.1.4"

**Comment by ZeeshanAhmadKhalil** [comment]
Still getting this issue while building project in debug

```
/Users/uni/Library/Developer/Xcode/DerivedData/onerooms-bgskxgmuselbnmebjtfepfstmvmm/Build/Intermediates.noindex/onerooms.build/Debug-iphonesimulator/onerooms.build/DerivedSources/onerooms_vers.c module map file '/Users/uni/Library/Developer/Xcode/DerivedData/onerooms-bgskxgmuselbnmebjtfepfstmvmm/Build/Products/Debug-iphonesimulator/InputMask/InputMask.modulemap' not found
```

`"react-native-text-input-mask": "^3.1.4"`
